// worker/mirror/serialize.ts — the canonical NDJSON line for one stored event
// (M6-3, ENG-167): the TypeScript mirror of `server/msgd/events/serialize.py`'s
// `event_ndjson_line` + `serialize_stored_event`.
//
// BYTE PARITY IS THE CONTRACT. The desktop mirror's `streams/<id>/*.ndjson`
// must be byte-identical to what `msgctl pull` writes (which itself is
// byte-identical to the server's export writer), so `msgctl verify`, byte-level
// diffs across clients, and the §9 bundle story all hold on the desktop log.
// The Python form is:
//
//   json.dumps(evt, ensure_ascii=False, separators=(",", ":")) + "\n"
//
// whose byte behavior `JSON.stringify` matches exactly on the served-event
// domain: compact separators, raw (unescaped) non-ASCII, the same short
// escapes (\" \\ \n \r \t \b \f) and lowercase \u00XX for other control
// chars, DEL (0x7f) unescaped, and ES6 `Number::toString` for numbers (which
// coincides with Python's repr on every JSON-round-tripped double). The frozen
// fixtures in `web/tests/fixtures/ndjson/` — GENERATED by the Python
// serializer — pin this byte-for-byte.
//
// `body` is passed through VERBATIM (raw-hash discipline, D1): it is the exact
// parsed value the wire carried, so its key order — as normalized by Postgres
// JSONB and preserved by JSON.parse — survives untouched and
// `hash_event(body) == event_hash` keeps holding on the written line. The
// ENVELOPE level, by contrast, is rebuilt explicitly in the one canonical key
// order `{body, event_hash, signature, server:{server_sequence,
// server_received_at, payload_redacted}}` (the `serialize_stored_event`
// shape), so the line's envelope framing can never drift.

import type { StoredEnvelope } from '../types'

/**
 * One NDJSON log line for a served event — compact JSON + `"\n"`, byte-equal
 * to `msgctl pull` / the server export writer for the same envelope.
 *
 * @throws {Error} when the envelope lacks the served-event essentials
 *   (`event_hash`, `server.server_sequence`, `server.server_received_at`) — an
 *   envelope without them is not a server-served event and must never reach
 *   the durable log.
 */
export function eventNdjsonLine(event: StoredEnvelope): string {
  const server = event.server
  if (
    typeof event.event_hash !== 'string' ||
    !server ||
    typeof server.server_sequence !== 'number' ||
    typeof server.server_received_at !== 'string'
  ) {
    throw new Error('eventNdjsonLine: not a server-served envelope (missing hash/server metadata)')
  }
  // Envelope-level key order pinned to `serialize_stored_event`; any extra
  // (future, D9-tolerated) `server` keys ride after the three canonical ones
  // in their wire order.
  const { server_sequence, server_received_at, payload_redacted, ...serverRest } = server
  const ordered = {
    body: event.body,
    event_hash: event.event_hash,
    signature: event.signature ?? null,
    server: {
      server_sequence,
      server_received_at,
      payload_redacted: payload_redacted ?? false,
      ...serverRest,
    },
  }
  return JSON.stringify(ordered) + '\n'
}
