// @vitest-environment node
//
// M6-3 (ENG-167) byte-parity gate: `eventNdjsonLine` must reproduce, byte for
// byte, the lines the PYTHON reference writes (`msgd.events.serialize.
// event_ndjson_line` — the exact bytes `msgctl pull` and the §9 export writer
// put on disk). The frozen fixture `tests/fixtures/ndjson/parity.ndjson` was
// GENERATED by that Python serializer (see generate_parity_fixture.py beside
// it); this runner parses each line — exactly what the wire hands the sync
// engine — re-serializes it through the TS twin, and compares raw UTF-8 bytes.
//
// Runs under `node` (crypto.subtle for the hash re-check + fs for the fixture),
// like vectors.spec.ts.

import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { hashEvent, type JSONValue } from '../../../src/core'
import { eventNdjsonLine } from '../../../src/worker/mirror/serialize'
import type { StoredEnvelope } from '../../../src/worker/types'

const fixturePath = fileURLToPath(new URL('../../fixtures/ndjson/parity.ndjson', import.meta.url))

if (!existsSync(fixturePath)) {
  throw new Error(
    `NDJSON parity fixture not found at ${fixturePath}. Regenerate with ` +
      '`uv run python web/tests/fixtures/ndjson/generate_parity_fixture.py` from the repo root.',
  )
}

const raw = readFileSync(fixturePath, 'utf8')
const lines = raw.split('\n').filter((l) => l.length > 0)

describe('eventNdjsonLine — byte parity with the server serializer (msgctl pull)', () => {
  it('fixture is non-trivial and newline-terminated', () => {
    expect(lines.length).toBeGreaterThanOrEqual(5)
    expect(raw.endsWith('\n')).toBe(true)
  })

  it.each(lines.map((line, i) => [i + 1, line] as const))(
    'vector %d round-trips byte-for-byte',
    (_n, line) => {
      const envelope = JSON.parse(line) as StoredEnvelope
      const out = eventNdjsonLine(envelope)
      // Compare BYTES, not JS strings — the log is a byte-level contract.
      expect(Buffer.from(out, 'utf8').equals(Buffer.from(line + '\n', 'utf8'))).toBe(true)
    },
  )

  it.each(lines.map((line, i) => [i + 1, line] as const))(
    'vector %d event_hash re-verifies over the raw parsed body (D1)',
    async (_n, line) => {
      const envelope = JSON.parse(line) as StoredEnvelope
      expect(await hashEvent(envelope.body as unknown as JSONValue)).toBe(envelope.event_hash)
    },
  )

  it('rejects an envelope without served-event server metadata', () => {
    const parsed = JSON.parse(lines[0]!) as StoredEnvelope
    expect(() => eventNdjsonLine({ body: parsed.body })).toThrow(/server-served/)
  })

  it('pins the envelope-level key order even when the input is shuffled', () => {
    const parsed = JSON.parse(lines[0]!) as StoredEnvelope
    const shuffled = {
      server: parsed.server,
      signature: parsed.signature,
      body: parsed.body,
      event_hash: parsed.event_hash,
    } as StoredEnvelope
    expect(eventNdjsonLine(shuffled)).toBe(lines[0]! + '\n')
  })
})
