"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-05 13:46:31.282343

Reproduces TDD §4.2 verbatim (ENG-63). Autogenerated, then hand-reviewed
column-for-column against §4.2 lines 317-433: the ``messages_proj.search_tsv``
GENERATED column (``Computed(persisted=True)`` -> ``GENERATED ALWAYS AS ...
STORED``) and its GIN index, all ``server_default now()``, the three CHECK
constraints (users.role, streams.kind, streams.visibility), the ``events``
composite PK ``(stream_id, server_sequence)`` + ``UNIQUE (workspace_id,
event_id)``, and the ``files`` / ``messages_proj`` indexes. FKs are declared
only where §4.2 writes ``REFERENCES``. The ``test_migrations`` compare_metadata
check locks models == this migration forever.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("file_id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("uploaded_by", sa.Text(), nullable=False),
        sa.Column("stream_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("file_id", name=op.f("pk_files")),
    )
    op.create_index(
        "ix_files_workspace_id_sha256", "files", ["workspace_id", "sha256"], unique=False
    )
    op.create_table(
        "invites",
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), server_default=sa.text("'member'"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_by", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_invites")),
    )
    op.create_table(
        "messages_proj",
        sa.Column("message_id", sa.Text(), nullable=False),
        sa.Column("stream_id", sa.Text(), nullable=False),
        sa.Column("thread_root_id", sa.Text(), nullable=True),
        sa.Column("author_user_id", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_seq", sa.BigInteger(), nullable=False),
        sa.Column("edited_seq", sa.BigInteger(), nullable=True),
        sa.Column("deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("reply_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_reply_seq", sa.BigInteger(), nullable=True),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', text)", persisted=True),
            nullable=True,  # §4.2 declares no NOT NULL on the generated column
        ),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_messages_proj")),
    )
    op.create_index(
        "ix_messages_proj_search_tsv",
        "messages_proj",
        ["search_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "read_state",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("stream_id", sa.Text(), nullable=False),
        sa.Column("last_read_seq", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "stream_id", name=op.f("pk_read_state")),
    )
    op.create_table(
        "workspaces",
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "file_quota_bytes",
            sa.BigInteger(),
            server_default=sa.text("10737418240"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_workspaces")),
    )
    op.create_table(
        "streams",
        sa.Column("stream_id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("visibility", sa.Text(), nullable=True),
        sa.Column("head_seq", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('workspace-meta','channel','dm')", name=op.f("ck_streams_kind_valid")
        ),
        sa.CheckConstraint(
            "visibility IN ('public','private')", name=op.f("ck_streams_visibility_valid")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_streams_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("stream_id", name=op.f("pk_streams")),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("is_bot", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role IN ('owner','admin','member','guest')", name=op.f("ck_users_role_valid")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.workspace_id"],
            name=op.f("fk_users_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
        sa.UniqueConstraint("workspace_id", "email", name=op.f("uq_users_workspace_id")),
    )
    op.create_table(
        "devices",
        sa.Column("device_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("public_key", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("fk_devices_user_id_users")
        ),
        sa.PrimaryKeyConstraint("device_id", name=op.f("pk_devices")),
    )
    op.create_table(
        "events",
        sa.Column("workspace_id", sa.Text(), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("stream_id", sa.Text(), nullable=False),
        sa.Column("server_sequence", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("type_version", sa.Integer(), nullable=False),
        sa.Column("author_user_id", sa.Text(), nullable=False),
        sa.Column("author_device_id", sa.Text(), nullable=False),
        sa.Column("client_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "server_received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_hash", sa.Text(), nullable=False),
        sa.Column(
            "payload_redacted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["stream_id"], ["streams.stream_id"], name=op.f("fk_events_stream_id_streams")
        ),
        sa.PrimaryKeyConstraint("stream_id", "server_sequence", name=op.f("pk_events")),
        sa.UniqueConstraint("workspace_id", "event_id", name=op.f("uq_events_workspace_id")),
    )
    op.create_table(
        "stream_members",
        sa.Column("stream_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["stream_id"], ["streams.stream_id"], name=op.f("fk_stream_members_stream_id_streams")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("fk_stream_members_user_id_users")
        ),
        sa.PrimaryKeyConstraint("stream_id", "user_id", name=op.f("pk_stream_members")),
    )
    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("device_id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.device_id"], name=op.f("fk_sessions_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("fk_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_sessions")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    op.drop_table("stream_members")
    op.drop_table("events")
    op.drop_table("devices")
    op.drop_table("users")
    op.drop_table("streams")
    op.drop_table("workspaces")
    op.drop_table("read_state")
    op.drop_index("ix_messages_proj_search_tsv", table_name="messages_proj", postgresql_using="gin")
    op.drop_table("messages_proj")
    op.drop_table("invites")
    op.drop_index("ix_files_workspace_id_sha256", table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
